/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 EarthOnly_0714.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/EarthOnly_0714-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Globe.geometry} material={nodes.Globe.material} position={[0, -0.06, 0]} />
      <mesh geometry={nodes.head001.geometry} material={nodes.head001.material} position={[-0.39, 0.12, -0.9]} rotation={[0.77, -1.1, 2.11]} scale={0.28} />
    </group>
  )
}

useGLTF.preload('/EarthOnly_0714-transformed.glb')
