/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Earth_0713.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Earth_0713.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pin.geometry} material={materials.pin} position={[-0.1, 0.31, 0.91]} rotation={[1.19, 0.05, 0.08]} scale={0.27} />
      <mesh geometry={nodes.pin001.geometry} material={materials.pin} position={[-0.58, 0.48, 0.61]} rotation={[0.9, -0.04, 0.62]} scale={0.27} />
      <mesh geometry={nodes.pin002.geometry} material={materials.pin} position={[-0.87, 0.37, 0.23]} rotation={[0.8, -0.15, 1.1]} scale={0.27} />
      <mesh geometry={nodes.pin003.geometry} material={materials.pin} position={[-0.62, -0.11, -0.78]} rotation={[0.86, -0.64, 2.25]} scale={0.27} />
      <mesh geometry={nodes.Globe.geometry} material={materials['Material.001']} position={[0, -0.06, 0]} />
    </group>
  )
}

useGLTF.preload('/Earth_0713.glb')
