/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Earth_0714.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Earth_0714.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Globe.geometry} material={materials['Material.001']} position={[0, -0.06, 0]} />
      <mesh name="Venezuela" geometry={nodes.Venezuela.geometry} material={nodes.Venezuela.material} morphTargetDictionary={nodes.Venezuela.morphTargetDictionary} morphTargetInfluences={nodes.Venezuela.morphTargetInfluences} position={[-0.41, 0.07, -0.9]} rotation={[1.55, -0.33, -0.44]} scale={-0.02} />
    </group>
  )
}

useGLTF.preload('/Earth_0714.glb')
