/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Earth_0711.glb -K -k
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Earth_0711.glb");

  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Globe"
          geometry={nodes.Globe.geometry}
          material={nodes.Globe.material}
        />
        <mesh
          name="Venezuela"
          geometry={nodes.Venezuela.geometry}
          material={nodes.Venezuela.material}
          position={[0.42, 0.12, 0.95]}
          rotation={[1.26, -0.31, -0.42]}
        />
        <mesh
          name="Morocco"
          geometry={nodes.Morocco.geometry}
          material={nodes.Morocco.material}
          position={[0.85, 0.49, 0.15]}
          rotation={[2.72, 0.36, 1.13]}
        />
        <mesh
          name="Nova_Scotia"
          geometry={nodes.Nova_Scotia.geometry}
          material={nodes.Nova_Scotia.material}
          position={[0.34, 0.68, 0.61]}
          rotation={[-2.99, 0.95, 0.65]}
        />
        <mesh
          name="Kenya"
          geometry={nodes.Kenya.geometry}
          material={nodes.Kenya.material}
          position={[0.81, -0.04, -0.62]}
          rotation={[-2.84, -0.63, 1.74]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Earth_0711.glb");
