/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Rose_0714.glb -T
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Rose_0714-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh name="Rose" geometry={nodes.Rose.geometry} material={nodes.Rose.material} morphTargetDictionary={nodes.Rose.morphTargetDictionary} morphTargetInfluences={nodes.Rose.morphTargetInfluences} position={[-0.41, 0.07, -0.9]} rotation={[1.55, -0.33, -0.44]} scale={-0.02} />
    </group>
  )
}

useGLTF.preload('/Rose_0714-transformed.glb')
